project_id = "iadhngzglwnfinocixdm"

[functions.run-analysis]
verify_jwt = false

[functions.interpret-results]
verify_jwt = false

[functions.check-assumptions]
verify_jwt = false

[functions.detect-variables]
verify_jwt = false

[functions.suggest-analysis]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-report]
verify_jwt = false
